name: "Measure JavaScript Size"
description: "Measure the total size of JavaScript files in a project's build directory."
inputs:
  build_dir:
    description: "Directory where the build files are located"
    required: true
outputs:
  js_size_kb:
    description: "Total JavaScript size in KB"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "logo"
  color: "yellow"
